# Pacman configuration for CarbonOS archiso build
[options]
HoldPkg     = pacman glibc
Architecture = auto

# Pacman output styling
Color
ILoveCandy
CheckSpace
VerbosePkgLists
ParallelDownloads = 5

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
